[package]
name = "example"
version = "0.1.0"
authors = ["Jan Šrámek <jan.sramek.ix@gmail.com>"]

[[bin]]
name = "example"
path = "example.rs"

[dependencies]
win-acl-rs = { path = "../../win-acl-rs" }